let data, current=0, style='bmp', image, mask, tool=null, dirty=false, drawing=false, undo=[], configDirty=false;
const $=id=>document.getElementById(id), ctx=$('overlay').getContext('2d'), mctx=$('mask-preview').getContext('2d');
const statusNames={pending:'待审核',accepted:'已确认',rejected:'需重做'};
const message=text=>$('message').textContent=text;
async function api(path,payload){const r=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const doc=await r.json();if(!r.ok)throw Error(doc.error||'读取失败');return doc;}
function img(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('图片未加载，请刷新'));im.src=url;});}
function selected(){return data.samples[current];}
function sceneUrl(name){return `/scene/${selected().id}/${name}.png?v=${selected().revision}-${Date.now()}`;}
async function refresh(){data=await api('/api/summary');$('progress').textContent=`已确认 ${data.accepted} / ${data.samples.length} 张 · ${data.accepted===data.samples.length?'本轮影像与边界验收完成':'其余保留待审或重做'}`; $('review-count').textContent=`${data.accepted} 张确认`;$('reviewed').classList.toggle('disabled',!data.accepted);$('reviewed').setAttribute('aria-disabled',String(!data.accepted));renderList();}
function renderList(){const list=$('samples');list.replaceChildren();data.samples.forEach((s,i)=>{const b=document.createElement('button');b.className='sample'+(i===current?' selected':'');b.setAttribute('aria-label',`${s.id} ${s.case_name} ${statusNames[s.review.status]}`);const thumb=document.createElement('img');thumb.src=`/scene/${s.id}/${s.config.style}.png?v=${s.revision}`;thumb.alt='';const label=document.createElement('span');label.className='label';const id=document.createElement('strong');id.textContent=s.id;const caseText=document.createElement('span');caseText.className='case';caseText.textContent=s.case_name;const small=document.createElement('small');small.textContent=s.config.style==='bmp'?'BMP 外观':'研究图外观';label.append(id,caseText,small);const st=document.createElement('span');st.className=`status ${s.review.status}`;st.textContent={pending:'○',accepted:'✓',rejected:'↻'}[s.review.status];b.append(thumb,label,st);b.onclick=()=>choose(i);list.append(b);});}
async function choose(i){if(dirty&&!confirm('这张的画笔修正尚未保存，是否放弃？'))return; current=i;dirty=false;undo=[];tool=null;configDirty=false;const s=selected();style=s.config.style;renderList();$('sample-id').textContent=`${s.id} / 20 · 第 ${s.revision} 版`;$('scene-title').textContent=s.case_name;$('scene-info').textContent=`${s.config.size} × ${s.config.size} · 区域边长 ${s.config.extent_m} m · 沉降约 ${s.source_cycles.toFixed(1)} 圈 · ${s.config.water?'含合成水体':'无水体'}`;$('selected-style').textContent=`导出使用：${s.config.style==='bmp'?'BMP 外观':'研究图外观'}；切换仅供对照`;$('note').value=s.review.note;$('threshold').value=Math.min(10,s.review.threshold_rad);$('threshold-value').textContent=s.review.threshold_rad.toFixed(2)+' rad';$('decision-status').textContent=statusNames[s.review.status];$('boundary-status').textContent=s.review.manual_mask?'已保存手工修正':s.review.status==='accepted'?'边界已确认':'候选线待确认';$('previous').disabled=i===0;$('next').disabled=i===data.samples.length-1;
const form=$('config');form.elements.footprint.value=s.config.footprint||'rectangular';Object.entries(s.config).forEach(([key,value])=>{const field=form.elements.namedItem(key);if(field){if(field.type==='checkbox')field.checked=value;else field.value=value;}});$('config-status').textContent=/3\.0$/.test(data.engine)?'新图已保存，可正常审核；继续生成需重启本地服务':'旧版本会保留，新版本需重新确认';updateTools();await loadImages();$('truth').src=sceneUrl('delta_down_m');$('dem').src=sceneUrl('dem_m');$('coherence').src=sceneUrl('estimated_coherence');const meta=await api(`/api/sample/${s.id}`);$('science-data').textContent=`种子 ${s.config.seed} · 空间间距 ${meta.pixel_spacing_m.toFixed(2)} m/px · 峰值沉降增量 ${meta.peak_down_mm.toFixed(1)} mm\n平均模型相干程度 ${meta.mean_model_coherence.toFixed(3)} · 工作面数量 ${meta.faces.filter(f=>f.enabled).length}\n标签规则：${s.review.manual_mask?'精确手工栅格范围':`无噪声形变相位绝对值 ≥ ${s.review.threshold_rad.toFixed(2)} rad（候选轮廓）`}\n${meta.warnings.join('\n')}`;}
async function loadImages(){const s=selected();$('view-bmp').classList.toggle('active',style==='bmp');$('view-research').classList.toggle('active',style==='research');image=await img(sceneUrl(style));$('input').src=image.src;const maskIm=await img(sceneUrl('mask'));const tmp=document.createElement('canvas');tmp.width=tmp.height=s.config.size;const c=tmp.getContext('2d');c.drawImage(maskIm,0,0);const pixels=c.getImageData(0,0,tmp.width,tmp.height).data;mask=new Uint8Array(tmp.width*tmp.height);for(let i=0;i<mask.length;i++)mask[i]=pixels[i*4]>=128?1:0;$('overlay').width=$('overlay').height=$('mask-preview').width=$('mask-preview').height=s.config.size;draw();loadZoom();}
function loadZoom(){for(const kind of ["input","wide","current","tight"])$("zoom-"+kind).src=sceneUrl(`crop_${style}_${kind}`);$("zoom-note").textContent=selected().review.manual_mask?"宽/紧对照会重建轮廓；手工边界不会自动改变":selected().review.status==="accepted"?"当前标签已确认；对照不会自动替换":"当前线待你判断";}
function draw(){if(!mask||!image)return;const n=selected().config.size;ctx.drawImage(image,0,0,n,n);const label=mctx.createImageData(n,n);const marks=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=y*n+x,v=mask[i]*255;label.data.set([v,v,v,255],i*4);if(mask[i]&&(x===0||x===n-1||y===0||y===n-1||!mask[i-1]||!mask[i+1]||!mask[i-n]||!mask[i+n]))marks.push([x,y]);}mctx.putImageData(label,0,0);ctx.fillStyle='black';for(const [x,y] of marks)ctx.fillRect(x-1,y-1,3,3);ctx.fillStyle='white';for(const [x,y] of marks)ctx.fillRect(x,y,1,1);updateTools();}
function updateTools(){$('generate').disabled=/3\.0$/.test(data?.engine||'');$('random-seed').disabled=$('generate').disabled;$('save-mask').disabled=!dirty;$('undo').disabled=!undo.length;for(const t of ['brush','erase']){$(t).classList.toggle('active',tool===t);$(t).setAttribute('aria-pressed',String(tool===t));}$('overlay').style.cursor=tool?'crosshair':'default';$('boundary-status').textContent=dirty?'修正尚未保存':selected()?.review.manual_mask?'已保存手工修正':selected()?.review.status==='accepted'?'边界已确认':'候选线待确认';}
function point(e){const r=$('overlay').getBoundingClientRect(),n=selected().config.size;return [(e.clientX-r.left)*n/r.width,(e.clientY-r.top)*n/r.height];}
let lastPoint;
function paintAt(x,y){const n=selected().config.size,r=Math.max(.5,Math.min(40,Number($('brush-size').value)||5)/2);for(let yy=Math.max(0,Math.floor(y-r));yy<Math.min(n,Math.ceil(y+r));yy++)for(let xx=Math.max(0,Math.floor(x-r));xx<Math.min(n,Math.ceil(x+r));xx++){if((xx+.5-x)**2+(yy+.5-y)**2<=r*r)mask[yy*n+xx]=tool==='brush'?1:0;}}
$('overlay').onpointerdown=e=>{if(!tool)return;undo.push(mask.slice());if(undo.length>30)undo.shift();drawing=true;lastPoint=point(e);paintAt(...lastPoint);dirty=true;$('overlay').setPointerCapture(e.pointerId);draw();};$('overlay').onpointermove=e=>{if(!drawing)return;const p=point(e),dist=Math.hypot(p[0]-lastPoint[0],p[1]-lastPoint[1]);const steps=Math.max(1,Math.ceil(dist));for(let k=1;k<=steps;k++)paintAt(lastPoint[0]+(p[0]-lastPoint[0])*k/steps,lastPoint[1]+(p[1]-lastPoint[1])*k/steps);lastPoint=p;draw();};$('overlay').onpointerup=$('overlay').onpointercancel=()=>{drawing=false;};
for(const t of ['brush','erase'])$(t).onclick=()=>{tool=tool===t?null:t;updateTools();};$('undo').onclick=()=>{mask=undo.pop();dirty=true;draw();};$('threshold').oninput=()=>{$('threshold-value').textContent=Number($('threshold').value).toFixed(2)+' rad';};
async function saveMask(){const payload={threshold_rad:selected().review.threshold_rad,mask_png:$('mask-preview').toDataURL('image/png'),note:$('note').value};await api(`/api/boundary/${selected().id}`,payload);dirty=false;undo=[];await refresh();$('decision-status').textContent='待审核';updateTools();loadZoom();}
$('save-mask').onclick=()=>busy(saveMask,'手工边界已保存，待确认');$('apply-threshold').onclick=()=>busy(async()=>{if(dirty&&!confirm('应用轮廓会替换未保存的画笔修正，是否继续？'))return;await api(`/api/boundary/${selected().id}`,{threshold_rad:Number($('threshold').value),note:$('note').value});dirty=false;await refresh();await choose(current);},'候选范围已更新');
for(const [id,status] of [['accept','accepted'],['reject','rejected'],['pending','pending']])$(id).onclick=()=>busy(async()=>{if(configDirty)throw Error('参数已修改，请先重新生成，或切换回当前样本');if(dirty)await saveMask();await api(`/api/decision/${selected().id}`,{status,note:$('note').value});await refresh();$('decision-status').textContent=statusNames[status];updateTools();},status==='accepted'?'这张的影像与边界已确认，已加入训练样本导出。':'意见已记录，样本保留。');
$('previous').onclick=()=>choose(current-1);$('next').onclick=()=>choose(current+1);
for(const s of ['bmp','research'])$('view-'+s).onclick=()=>busy(async()=>{if(dirty)throw Error('请先保存边界修正，再切换外观');style=s;await loadImages();},'');
$('simple').onclick=()=>{$('advanced').classList.remove('active');$('simple').classList.add('active');document.querySelector('.advanced-fields').hidden=true;};$('advanced').onclick=()=>{$('simple').classList.remove('active');$('advanced').classList.add('active');document.querySelector('.advanced-fields').hidden=false;};
$('config').oninput=()=>{configDirty=true;$('config-status').textContent='参数已修改，点击重新生成后生效';};$('random-seed').onclick=()=>{const values=new Uint32Array(1);crypto.getRandomValues(values);$('config').elements.seed.value=values[0];configDirty=true;$('config-status').textContent='新随机种子已选，点击重新生成';};
$('config').onsubmit=e=>{e.preventDefault();busy(async()=>{if(dirty&&!confirm('边界未保存，重新生成会保留旧文件，但丢弃未保存笔画。是否继续？'))return;if(/3\.0$/.test(data.engine))throw Error('新图可正常审核；继续生成需重启本地服务');const form=$('config'),config={...selected().config,boundary_rad:selected().review.threshold_rad,footprint:form.elements.footprint.value};for(const key of Object.keys(config)){const f=form.elements.namedItem(key);if(f)config[key]=f.type==='checkbox'?f.checked:f.tagName==='SELECT'&&['case','footprint'].includes(key)?f.value:Number(f.value);}message('正在生成新版本，旧版已保留…');await api(`/api/regenerate/${selected().id}`,config);dirty=false;await refresh();await choose(current);},'新版本已生成；请重新看影像与边界。');};
async function busy(action,success){const buttons=document.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await action();message(success||'');}catch(e){message(e.message);}finally{buttons.forEach(b=>b.disabled=false);$('previous').disabled=current===0;$('next').disabled=current===data.samples.length-1;updateTools();}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
refresh().then(()=>choose(0)).catch(e=>message(e.message));

for(const [id,factor] of [["widen",.5],["tighten",2],["default-boundary",0]])$(id).onclick=()=>busy(async()=>{if(dirty&&!confirm("这会替换未保存的画笔修正，是否继续？"))return;const t=factor?Math.max(.02,Math.min(10,selected().review.threshold_rad*factor)):(data.boundary_policy?.recommended_threshold_rad||.8);await api(`/api/boundary/${selected().id}`,{threshold_rad:t,note:$("note").value});dirty=false;await refresh();await choose(current);},"候选边界已调整，请看最外圈是否完整。");
